In [5]:
#Import required mocules
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
#Load dataset
df = pd.read_csv("../Dataset/Breast_Cancer.csv")

#Show first 5 rows
df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [11]:
#Check the basic structure of the dataset
df.shape
df.columns
df.info()
df.describe()

#Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   str
 2   Marital Status          4024 non-null   str
 3   T Stage                 4024 non-null   str
 4   N Stage                 4024 non-null   str
 5   6th Stage               4024 non-null   str
 6   differentiate           4024 non-null   str
 7   Grade                   4024 non-null   str
 8   A Stage                 4024 non-null   str
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   str
 11  Progesterone Status     4024 non-null   str
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   str
dtypes: int64(5), str(11)
memory usage: 503.1 KB

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [12]:
#Encode target variable
df["Status"] = df["Status"].map({"Alive": 1, "Dead": 0})

#Check result
df["Status"].value_counts()

Status
1    3408
0     616
Name: count, dtype: int64

In [13]:
#Identify categorical columns
cat_cols = df.select_dtypes(include=["object"]).columns
cat_cols

C:\Users\sharalaj\AppData\Local\Temp\ipykernel_12452\2162732519.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=["object"]).columns

Index(['Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Estrogen Status',
       'Progesterone Status'],
      dtype='str')

In [14]:
# Apply one-hot encoding
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

# Check new structure
df.head()

,Age,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months,Status,Race_Other,Race_White,Marital Status_Married,Marital Status_Separated,...,6th Stage_IIIC,differentiate_Poorly differentiated,differentiate_Undifferentiated,differentiate_Well differentiated,Grade_1,Grade_2,Grade_3,A Stage_Regional,Estrogen Status_Positive,Progesterone Status_Positive
0,68,4,24,1,60,1,False,True,True,False,...,False,True,False,False,False,False,True,True,True,True
1,50,35,14,5,62,1,False,True,True,False,...,False,False,False,False,False,True,False,True,True,True
2,58,63,14,7,75,1,False,True,False,False,...,True,False,False,False,False,True,False,True,True,True
3,58,18,2,1,84,1,False,True,True,False,...,False,True,False,False,False,False,True,True,True,True
4,47,41,3,1,50,1,False,True,True,False,...,False,True,False,False,False,False,True,True,True,True

In [15]:
#Seperate features and target

#Split features and target
X = df.drop("Status", axis=1)
y = df["Status"]

#Check shapes
X.shape, y.shape

((4024, 29), (4024,))